### ISSUE TITLE
[BUG] can not delete point

### ISSUE THREAD

**Issue by mdecourse** [KmolYuan/Pyslvs-UI#22]
1. Start pyslvs-19.09.0.post0.mscv1916-amd64.exe.
2. Bring up Arm example.
3. Try to delete Point 8 and system stop working.

![arm_example_crash_while_delete_point_8](https://user-images.githubusercontent.com/20835445/65810107-74c89a00-e1d8-11e9-954d-6cd2dfe226c4.png)

**Comment by KmolYuan** [comment]
Fixed with 33818373a43b53bc7882e7585641e96e69bebb6b in post-released version. This error might be exist from v19.07.
