### ISSUE TITLE
[ENH] Can we set a multi-point link as input?

### ISSUE THREAD

**Issue by mdecourse** [KmolYuan/Pyslvs-UI#24]
Can we set the L7 link as input?

![multiple-point_as_input](https://user-images.githubusercontent.com/20835445/65877947-76a08200-e3bf-11e9-9f8e-a73f9887606e.png)

**Comment by KmolYuan** [comment]
Yes, the input pair can be `Point5 -> Point3` or `Point5 -> Point4` for this case.

**Comment by mdecourse** [comment]
Thanks, got it!
