### ISSUE TITLE
[ENH] No model details were displayed when loading an existing pyslvs file.

### ISSUE THREAD

**Issue by mdecourse** [KmolYuan/Pyslvs-UI#25]
1. Start pyslvs-19.10.0.dev0.mscv1916-amd64.exe
2. Load the arm example.
3. The storage area displays the model details.
4. Save Arm as another file named Arm2.pyslvs
5. Load Arm2.pyslvs, the storage area is empty.

![arm_pyslvs](https://user-images.githubusercontent.com/20835445/65926926-2f031000-e42a-11e9-94d1-0bcb931b915a.png)
![arm2_pyslvs](https://user-images.githubusercontent.com/20835445/65926932-332f2d80-e42a-11e9-88d9-6b504989998c.png)

**Comment by KmolYuan** [comment]
"Storage list" has no included main mechanism before, because it's a container of disabled mechanism.

Add a new field to show current expression is needed.
