### ISSUE TITLE
[ENH] Import image file as template layer

### ISSUE THREAD

**Issue by mdecourse** [KmolYuan/Pyslvs-UI#26]
If the image file can be imported as a template layer, and can be toggled on and off. Users  can create the model more easily.

![mechanism_drawing_as_template](https://user-images.githubusercontent.com/20835445/65927748-835bbf00-e42d-11e9-8e5a-a37df260c591.png)
![pyslvs_design](https://user-images.githubusercontent.com/20835445/65927754-88207300-e42d-11e9-8b4e-fe858f7849c4.png)

**Comment by KmolYuan** [comment]
There's already has a "background" option in the program settings.

But as you said, this function can be moved into project files for convenience.

**Comment by KmolYuan** [comment]
Applied this feature at 421a91e9a24d1272fa5615b510e88926dceadd88 and 7ba91cf4e4f7ecbc07d97026c88712bfa820d177.
