### ISSUE TITLE
[BUG] Pyslvs crashed on import SLVS saved with nightly SolveSpace 3.0

### ISSUE THREAD

**Issue by Symbian9** [KmolYuan/Pyslvs-UI#28]
### Describe the bug

Pyslvs crashed on import SLVS saved with nightly SolveSpace 3.0

### To Reproduce

0. Create SLVS file using nightly build of SolveSpace 3.0;
1. Launch Pyslvs
2. Go to "File > Load File"
3. Select "Solvespace module"; (NOTE: Typo mistake - should be named as "SolveSpace 2.0")
4. Select SLVS file created using nightly build of SolveSpace 3.0;
5. Push "Open" button;
6. Pyslvs silently crashed immediately.

### Terminal Log

<details>

```
$ ./pyslvs-19.09.0.post0.glibc2.3.3-x86_64.AppImage
Pyslvs 19.09.0.post0
OS Type: Linux 4.15.0-1-amd64 [x86_64]
Python Version: 3.8.0(beta)
Python Compiler: GCC 5.4.0 20160609
Qt wrapper: PyQt5 5.13.1
Qt Version: 5.13.0
-------

Startup with: 7.31s
Connect to GUI console.
Traceback (most recent call last):
  File "/var/tmp/.mount_pyslvswdOJEE/usr/bin/pyslvs_ui/core/main_window/io.py", line 319, in __load_file
    self.__read_slvs(file_name)
  File "/var/tmp/.mount_pyslvswdOJEE/usr/bin/pyslvs_ui/core/main_window/io.py", line 108, in __read_slvs
    self.parse_expression(parser.parse(group.split('@')[0]))
  File "/var/tmp/.mount_pyslvswdOJEE/usr/bin/pyslvs_ui/core/io/slvs/read.py", line 111, in parse
    entity['Entity.actPoint.x'],
KeyError: 'Entity.actPoint.x'
Aborted
```

</details>

### Expected behavior

Pyslvs should load SolveSpace 3.0 file format.

Possibly, need create separate import options for "SolveSpace 2.0 module" and "SolveSpace 3.0 module"

### Desktop

 - OS: *Linux (Debian 9.x, x86_64)*
 - Version: `19.09.0`

### Additional context

Sample SLVS - https://gist.github.com/Symbian9/cdc817e7f33f3eabd66ea04e032b3342

Nightly builds of SolveSpace 3.0:

- for Linux (PPA) - https://notesalexp.org/
- for Windows - https://ci.appveyor.com/project/whitequark/solvespace/build/artifacts

**Comment by KmolYuan** [comment]
In the nightly builds, the value equals zero will be removed in the file, so use "dict.get" method instead of "get item" operator.
