### ISSUE TITLE
[BUG] release v20.08.0 Mac OS 10.15.1 版本启动闪退

### ISSUE THREAD

**Issue by apachecd** [KmolYuan/Pyslvs-UI#37]
**Describe the bug**
v20.08.0 Mac Release 版本 在  Mac OS 10.15.1 上启动后会直接崩溃退出,没有任何提示.

PS. 如果哪位恰巧看到这条信息,并想在北京找一份机械设计师的工作请跟看看我们公司,想必喜欢这个软件的人都是能力极强的.
http://www.autolabor.com.cn/join

**To Reproduce**
1. 解压下载的安装包
2. 点击启动程序
3. 程序直接退出

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: 10.15.1

**Additional context**

**Comment by KmolYuan** [comment]
This error is caused by X code version.
The version v20.08 is built in macOS `10.15.5`. ([AppVeyor environment](https://www.appveyor.com/docs/macos-images-software/))

I can use `macos-mojave` config (`10.14.6`) in next release.
Please use PyPI or other releases in this version.
