### ISSUE TITLE
pyslvs-20.08.0.mscv1924-amd64 建立pin in slot時閃退

### ISSUE THREAD

**Issue by tom-tseng** [KmolYuan/Pyslvs-UI#39]
操作系統:win10 64bit intel晶片
操作建立pin in slot時按下ok後 軟體閃退

![3](https://user-images.githubusercontent.com/73455823/97132937-4292be80-1783-11eb-906d-3f63fa1b4ebd.JPG)

**Comment by KmolYuan** [comment]
Same as #38.
