### ISSUE TITLE
[DOC] The docs don't seem to display well in Safari, Firefox, and Chrome (haven't tried more yet) 

### ISSUE THREAD

**Issue by ThijsRoumen** [KmolYuan/Pyslvs-UI#47]
When I open the documentation (https://pyslvs-ui.readthedocs.io/en/stable/python-solvespace-api/) I mostly see some huge search and code icons, it does show a menu but returns 404 errors as I navigate through it. I would love to dig in to this documentation though as I'm eager/curious to use the library for a course I am teaching on Algorithmic Folding (lecture = linkage folding)

so far I tested with Chrome, Firefox, and Safari, happy to test more if that helps 

I love this project, thanks so much for putting this together!

**Comment by ThijsRoumen** [comment]
P.S. it works fine when I download the repo and just run it locally

**Comment by KmolYuan** [comment]
Thanks for reminding. I have rebuilt the docs.
